AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: LMS Project - Course Service connected to manual tables

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: nodejs20.x

Resources:
  CourseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambdas/course/
      Handler: index.handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:Scan
                - dynamodb:UpdateItem
                - dynamodb:Query
                - dynamodb:BatchWriteItem
              Resource:
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/courses"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/courses/index/*"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/users"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/completions"
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"
      Events:
        CreateCourse:
          Type: Api
          Properties:
            Path: /courses
            Method: post
        ListCourses:
          Type: Api
          Properties:
            Path: /courses
            Method: get
        AssignCourse:
          Type: Api
          Properties:
            Path: /courses/{id}/assign
            Method: post

  QuizFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambdas/quiz/
      Handler: index.handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:GetItem
                - dynamodb:UpdateItem
              Resource:
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/quiz_answers"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/completions"
      Events:
        GetQuiz:
          Type: Api
          Properties:
            Path: /courses/{id}/quiz
            Method: get
        SubmitQuiz:
          Type: Api
          Properties:
            Path: /courses/{id}/quiz/submit
            Method: post
Outputs:
  CourseApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
